apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-role-binding
subjects:
- kind: ServiceAccount
  name: pod-creator
roleRef:
  kind: Role
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-creator-pod
spec:
  serviceAccountName: pod-creator
  containers:
  - name: brightside
    image: python:latest
    # command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]  # Keep the container running
    command: ["/bin/sh", "-c", "cd /app ; pip install -r requirements.txt ; python app.py"]  # Keep the container running
    stdin: true
    # imagePullPolicy: Never # for localy built image 
    ports:
      - containerPort: 5000
    volumeMounts:
      - name: app
        mountPath: /app

  volumes:
  - name: app
    hostPath:
      path: /app
      type: Directory
